### ISSUE TITLE
why sum(0)?

### ISSUE THREAD

**Issue by zzwang058** [rish-16/aft-pytorch#1]
Thank you for this code!
I got a problem with [this](https://github.com/rish-16/aft-pytorch/blob/main/aft_pytorch/aft_pytorch.py) at line 33 and line 36. Why **_sum(0)_** to add all batch dimension? I noticed that it add the timestep dimension from **_t=1_** to **_T_**, so maybe it should be sum(2) here.

**Comment by rish-16** [comment]
Hey, thanks for the catch / fix. I'll look into this.

**Comment by rish-16** [comment]
The patch has been made. Appreciate it :)
