### ISSUE TITLE
why wbias = nn.Parameter(torch.rand(self.heads, T, T)) in forward pass?

### ISSUE THREAD

**Issue by gaopengcuhk** [rish-16/aft-pytorch#3]

**Comment by rish-16** [comment]
Hey, thanks for bringing this up!

I usually don't add trainable param variables in the forward pass 😅 

I did this temporarily as I had no other way to pass in the number of timesteps in the sequence (ie, seq length). One fix would be to add `seqlen` as a param to the layer object constructor but that defeats the purpose of the module being sequence-length-invariant.

However, I'm in talks with the primary author of the paper at the moment to find a more elegant way to present this. If you have any feedback on that specifically, would love to know!

**Comment by rish-16** [comment]
So the author says I can instead of a `max_seqlen` param in the constructor that's pretty self-explanatory. 

This means users do not have to specify the number of timesteps every time they use `forward` or the layer in general. A trick the author told me about is using a temporary placeholder `wbias` tensor in `forward` that is resizeable according to the incoming sequences' lengths.

I'm working on a patch that introduces these fixes as of the last update. Should roll out soon!

**Comment by khel-kim** [comment]
Hi rish! Thank you for you work!

How about this to init parameters & pass seq length?

```python
class AFTFull(nn.Module):
    def __init__(self, dim, hidden_dim=64, heads=8):
    	...
       
        self.position_biases = nn.Parameter(self.heads, ENOUGH_SIZE, ENOUGH_SIZE)
        nn.init.xavier_uniform_(self.position_biases)
        
        ...


    def forward(self, x):
        B, T, _ = x.shape
        Q = self.to_q(x).view(B, self.heads, T, self.hidden_dim)
        K = self.to_k(x).view(B, self.heads, T, self.hidden_dim)
        V = self.to_v(x).view(B, self.heads, T, self.hidden_dim)
        
        # wbias = nn.Parameter(torch.rand(self.heads, T, T))
        wbias = nn.position_biases[:, :T, :T]
        
        ...

```

**Comment by rish-16** [comment]
Hello!

The latest commit addresses just this in a similar way using the `[:, :]`. I spoke to the author and he feels that it's best to use 1 head instead as done in the paper. I'll be changing the `wbias` initialisation using the factorized version shown in the paper using the `u` and `v` tensors.

Thank you again for the look-see! Will be closing this issue now :)
